export const data = [
  { id: 1, title: "Real State", imageAddress: "/images/home-pic.svg" },
  { id: 2, title: "Vehicle", imageAddress: "/images/vehicle-pic.svg" },
  { id: 3, title: "Spare Part", imageAddress: "/images/spare-part-pic.svg" },
  { id: 4, title: "Second Hand", imageAddress: "/images/second-hand-pic.svg" },
  {
    id: 5,
    title: "Construction",
    imageAddress: "/images/construction-pic.svg",
  },
  {
    id: 6,
    title: "Private Lesson",
    imageAddress: "/images/private-lesson-pic.svg",
  },
  { id: 7, title: "Job Posting", imageAddress: "/images/job-posting-pic.svg" },
  { id: 8, title: "Apple", imageAddress: "/images/apple-pic.svg" },
  { id: 9, title: "Apple", imageAddress: "/images/real-state-pic.svg" },
  { id: 10, title: "Helper", imageAddress: "/images/helper-pic.svg" },
  { id: 11, title: "Animals", imageAddress: "/images/animals-pic.svg" },
  { id: 12, title: "Cosmetics", imageAddress: "/images/cosmetics-pic.svg" },
  {
    id: 13,
    title: "Mother & Baby",
    imageAddress: "/images/mother-baby-pic.svg",
  },
  { id: 14, title: "Music", imageAddress: "/images/music-pic.svg" },
  { id: 15, title: "Sport", imageAddress: "/images/sport-pic.svg" },
  { id: 16, title: "Computer", imageAddress: "/images/computer-pic.svg" },
  {
    id: 17,
    title: "Food & Beverage",
    imageAddress: "/images/food-beverage.svg",
  },
  {
    id: 18,
    title: "Mobile Phone",
    imageAddress: "/images/mobile-phone-pic.svg",
  },
];

export const imageCard = [
  { id: "1", imageAddress: "/images/card-pic1.png" },
  { id: "2", imageAddress: "/images/card-pic2.png" },
  { id: "3", imageAddress: "/images/card-pic3.png" },
  { id: "4", imageAddress: "/images/card-pic4.png" },
  { id: "5", imageAddress: "/images/card-pic5.png" },
  { id: "6", imageAddress: "/images/card-pic6.png" },
  { id: "7", imageAddress: "/images/card-pic7.png" },
  { id: "8", imageAddress: "/images/card-pic8.png" },
  { id: "9", imageAddress: "/images/card-pic9.png" },
  { id: "10", imageAddress: "/images/card-pic10.png" },
  { id: "11", imageAddress: "/images/card-pic11.png" },
  { id: "12", imageAddress: "/images/card-pic12.png" },
  { id: "13", imageAddress: "/images/card-pic13.png" },
  { id: "14", imageAddress: "/images/card-pic14.png" },
  { id: "15", imageAddress: "/images/card-pic15.png" },
];
